# Generated by Django 4.0.5 on 2022-06-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('contact', models.CharField(max_length=150)),
                ('requirements', models.ManyToManyField(to='main_app.requirements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
