# Generated by Django 4.0.5 on 2022-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_requirements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverletter',
            field=models.URLField(default=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.URLField(default=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.TextField(default=True, max_length=5000),
        ),
    ]
