# Generated by Django 4.0.5 on 2022-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_coverletter_profile_cv_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverletter',
            field=models.URLField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.URLField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
