# Generated by Django 4.0.5 on 2022-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('applied', 'Application Sent'), ('interview', 'Interviewing'), ('success', 'Successful'), ('unsuccess', 'Unsuccessful')], default='New', max_length=10),
        ),
    ]
