# Generated by Django 4.0.5 on 2022-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback',
            field=models.TextField(default='', max_length=250),
        ),
    ]
