# Generated by Django 4.0.5 on 2022-06-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile_email_profile_name'),
        ('main_app', '0010_alter_job_status'),
    ]

    operations = [
    ]
