# Generated by Django 4.0.5 on 2022-06-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20220628_1435'),
        ('main_app', '0012_merge_20220628_1433'),
    ]

    operations = [
    ]
