# Generated by Django 4.0.5 on 2022-07-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
